services:
  # 1. Dịch vụ Database (PostgreSQL)
  database:
    image: postgres:12-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: my_fullstack_db
    ports:
      - "5433:5432" # Máy thật kết nối qua 5433, các container khác kết nối qua database:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  # 2. Dịch vụ Backend
  backend-app:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - my_network

  # 3. Dịch vụ Frontend
  frontend-app:
    build: ./frontend
    container_name: my_frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - my_network

volumes:
  postgres_data:

# Tạo một mạng chung để các container tự nhận diện tên của nhau
networks:
  my_network:
    driver: bridge